<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
/* check header type from config */
$dataHelper = $this->helper('Salecto2\Magento2FrontendTheme\Helper\Data');
$scope = 'theme';
$headerData = 'header_type';
$headerType = $dataHelper->getThemeConfig($scope, $headerData);
if(isset($headerType) && $headerType == 1) :
    echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Salecto2_Magento2FrontendTheme::html/header_type1.phtml")->toHtml();
endif;
if ($block->getShowPart() == 'welcome') : ?>
    <li class="greet welcome" data-bind="scope: 'customer'">
        <!-- ko if: customer().fullname  -->
        <span class="logged-in"
              data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
        </span>
        <!-- /ko -->
        <!-- ko ifnot: customer().fullname  -->
        <?= $block->getBlockHtml('header.additional') ?>
        <!-- /ko -->
    </li>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>
<?php elseif ($block->getShowPart() == 'other') :?>
    <?= $block->getChildHtml() ?>
<?php endif ?>